name: release-tarball
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Empaquetar repo (sin .git)
        run: |
          tar --exclude='.git' -czf app.tar.gz .
      - name: Crear release y subir asset
        uses: softprops/action-gh-release@v2
        with:
          files: app.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

